### ISSUE TITLE
Exporting to iCal

### ISSUE THREAD

**Issue by itskaitlynp** [raxod502/hyperschedule#184]
When exporting to iCal, only one course successfully imports, even though all of my courses are starred. I'm not sure if I'm doing something wrong, or if there is a bug here.

**Comment by kwshi** [comment]
Odds are there's a bug.  I'm a bit swamped for the next few weeks so I can't get around to fixing it, but I'll try to get to it as soon as I can!

**Comment by mia1024** [comment]
Closing as ical has been re-implemented in v2
