### ISSUE TITLE
Select Courses Not Appearing

### ISSUE THREAD

**Issue by lillee205** [raxod502/hyperschedule#185]
It seems like new classes such as the new HMC art classes and the renamed core classes (Chem42) are not showing up on the course listings.

**Comment by kwshi** [comment]
Hi!  Sorry for the delayed response.  I'm aware of the issue, but my hands are
(kind of) tied-- following #158, we no longer scrape our data from Portal but
rather receive it from HMC tech admin; the missing courses are simply missing in
the data they send us (and there are far too many such missing courses for us to manually find and correct).

I've sent them an email trying to get the data fixed, but they haven't responded
yet.  Beyond that, there's not much I can do...

**Comment by mia1024** [comment]
Fixed with the updated data source
